"""Add is_public column to Quiz model

Revision ID: a026231cd5f0
Revises: 7c88cd4ed2d8
Create Date: 2025-03-28 16:03:14.719023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a026231cd5f0'
down_revision = '7c88cd4ed2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
