"""add image_path to Question

Revision ID: e0eb8da71e3f
Revises: 
Create Date: 2025-04-08 15:53:05.828020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eb8da71e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)  # Cho phép null để tránh lỗi

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)  # Giữ nguyên nullable=True khi downgrade

    # ### end Alembic commands ###
